Repository luissimas/pooa-grupos-academicos, pull requests merged in 2022-09, with the labels that each got.

#9 listar membros do grupo, problemas nas factories
  src/application/usecases/academicGroup/listAcademicGroupMembersUsecase.ts
  src/factories/controller/academicGroup/listAcademicGroupMembersControllerFactory.ts
  src/factories/usecase/academicGroup/listAcademicGroupMembersFactory.ts
  src/http/controllers/academicGroup/listAcademicGroupMembersController.ts
  src/http/routes/academicGroup.ts
Labels: enhancement

#10 Feature/singleton
  src/factories/controller/academicGroup/addAcademicGroupMemberControllerFactory.ts
  src/factories/controller/academicGroup/createAcademicGroupControllerFactory.ts
  src/factories/controller/academicGroup/listAcademicGroupMembersControllerFactory.ts
  src/factories/controller/academicGroup/listAcademicGroupsByUserControllerFactory.ts
  src/factories/controller/auth/loginControllerFactory.ts
  src/factories/controller/user/createUserControllerFactory.ts
  src/factories/middlewares/authMiddlewareFactory.ts
  src/factories/usecase/academicGroup/addAcademicGroupMemberUsecaseFactory.ts
  src/factories/usecase/academicGroup/createAcademicGroupUsecaseFactory.ts
  src/factories/usecase/academicGroup/listAcademicGroupMembersUsecaseFactory.ts
  src/factories/usecase/academicGroup/listAcademicGroupsByUserUsecaseFactory.ts
  src/factories/usecase/auth/loginUsecaseFactory.ts
  src/factories/usecase/user/createUserUsecaseFactory.ts
  src/http/routes/academicGroup.ts
  src/http/routes/auth.ts
  src/http/routes/user.ts
  src/infra/auth/jwtAuthService.ts
  src/infra/id/uuidIdService.ts
  src/infra/password/bcryptPasswordService.ts
  src/infra/repositories/academicGroup/memoryAcademicGroupRepository.ts
  src/infra/repositories/classEnrollment/apiClassEnrollmentRepository.ts
  src/infra/repositories/user/memoryUserRepository.ts
Labels: enhancement

#11 Feature/disable academic group
  src/application/usecases/academicGroup/disableAcademicGroupUsecase.ts
  src/domain/errors/baseError.ts
  src/domain/errors/index.ts
  src/factories/controller/academicGroup/disableAcademicGroupControllerFactory.ts
  src/factories/usecase/academicGroup/disableAcademicGroupUsecaseFactory.ts
  src/http/controllers/academicGroup/disableAcademicGroupController.ts
  src/http/routes/academicGroup.ts
Labels: documentation, enhancement

#12 Feature/update academic group sponsor
  src/application/usecases/academicGroup/addAcademicGroupMemberUsecase.ts
  src/application/usecases/academicGroup/updateAcademicGroupSponsorUsecase.ts
  src/factories/controller/academicGroup/updateAcademicGroupSponsorControllerFactory.ts
  src/factories/usecase/academicGroup/updateAcademicGroupSponsorUsecaseFactory.ts
  src/http/controllers/academicGroup/updateAcademicGroupSponsorController.ts
  src/http/routes/academicGroup.ts
Labels: documentation, enhancement

#15 Feature/list academic group by
  src/application/usecases/academicGroup/listAcademicGroupByIdUsecase.ts
  src/factories/controller/academicGroup/listAcademicGroupByIdControllerFactory.ts
  src/factories/usecase/academicGroup/listAcademicGroupByIdUsecaseFactory.ts
  src/http/controllers/academicGroup/listAcademicGroupByIdController.ts
  src/http/routes/academicGroup.ts
Labels: enhancement, help wanted

#14 Feature/list academic groups
  src/application/usecases/academicGroup/listAcademicGroupsUsecase.ts
  src/factories/controller/academicGroup/listAcademicGroupsControllerFactory.ts
  src/factories/usecase/academicGroup/listAcademicGroupsUsecaseFactory.ts
  src/http/controllers/academicGroup/listAcademicGroupsController.ts
  src/http/routes/academicGroup.ts
Labels: enhancement, help wanted

#19 estrutura de remoção de pessoa de um grupo. Falta a rota
  src/application/usecases/academicGroup/removeAcademicGroupMemberUsecase.ts
  src/factories/controller/academicGroup/RemoveAcademicGroupMemberControllerFactory.ts
  src/factories/usecase/academicGroup/removeAcademicGroupMemberUsecaseFactory.ts
  src/http/controllers/academicGroup/removeAcademicGroupMemberController.ts
  src/http/routes/academicGroup.ts
Labels: documentation, enhancement

#18 Feature/list event by academic group
  src/application/repositories/EventRepository.ts
  src/application/usecases/event/listEventByAcademicGroupUsecase.ts
  src/domain/entities/event.ts
  src/factories/controller/event/ListEventByAcademicGroupControllerFactory.ts
  src/factories/usecase/event/listEventByAcademicGroupUsecaseFactory.ts
  src/http/controllers/event/listEventByAcademicGroupController.ts
  src/infra/repositories/event/memoryEventRepository.ts
Labels: documentation, enhancement

#20 feat: create event usecase
  src/application/usecases/event/createEventUsecase.ts
  src/factories/usecase/event/createEventUsecaseFactory.ts
Labels: enhancement

#22 feat: name filter on academic groups listing
  src/application/repositories/academicGroupRepository.ts
  src/application/usecases/academicGroup/listAcademicGroupsUsecase.ts
  src/http/controllers/academicGroup/listAcademicGroupsController.ts
  src/http/routes/academicGroup.ts
  src/infra/repositories/academicGroup/memoryAcademicGroupRepository.ts
Labels: documentation, enhancement
