Repository luissimas/pooa-grupos-academicos, pull requests merged in 2022-08, with the labels that each got.

#2 Camada http
  src/@types/express.d.ts
  src/app.ts
  src/http/adapters/expressControllerAdapter.ts
  src/http/adapters/expressErrorHandlerAdapter.ts
  src/http/adapters/expressMiddlewareAdapter.ts
  src/http/error/errorHandler.ts
  src/http/index.ts
  tsconfig.json
Labels: enhancement

#3 Feature/auth
  README.org
  package.json
  src/app.ts
  src/application/dtos/curso.ts
  src/application/dtos/user.ts
  src/application/repositories/userRepository.ts
  src/application/services/auth.ts
  src/application/services/id.ts
  src/application/services/password.ts
  src/application/usecases/auth/loginUsecase.ts
  src/application/usecases/index.ts
  src/application/usecases/user/createUserUsecase.ts
  src/domain/entities/aluno.ts
  src/domain/entities/curso.ts
  src/domain/entities/departamento.ts
  src/domain/entities/evento.ts
  src/domain/entities/grupoAcademico.ts
  src/domain/entities/local.ts
  src/domain/entities/processoSeletivo.ts
  src/domain/entities/professor.ts
  src/domain/entities/usuario.ts
  src/domain/errors/baseError.ts
  src/domain/errors/index.ts
  src/factories/controller/auth/loginControllerFactory.ts
  src/factories/controller/user/createUserControllerFactory.ts
  src/factories/middlewares/authMiddlewareFactory.ts
  src/factories/usecase/auth/loginUsecaseFactory.ts
  src/factories/usecase/user/createUserUsecaseFactory.ts
  src/http/controllers/auth/loginController.ts
  src/http/controllers/user/createUserController.ts
  src/http/error/errorHandler.ts
  src/http/index.ts
  src/http/middlewares/auth.ts
  src/http/routes/auth.ts
  src/http/routes/index.ts
  src/http/routes/user.ts
  src/infra/auth/jwtAuthService.ts
  src/infra/id/uuidIdService.ts
  src/infra/password/bcryptPasswordService.ts
  src/infra/repositories/user/memoryUserRepository.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#5 Feature/auth docs
  src/application/dtos/user.ts
  src/application/usecases/user/createUserUsecase.ts
  src/http/controllers/user/createUserController.ts
  src/http/routes/auth.ts
  src/http/routes/user.ts
Labels: documentation, enhancement

#6 Feature/criar grupo academico
  src/application/dtos/academicGroup.ts
  src/application/dtos/location.ts
  src/application/repositories/academicGroupRepository.ts
  src/application/usecases/academicGroup/createAcademicGroupUsecase.ts
  src/application/usecases/academicGroup/listAcademicGroupsByUserUsecase.ts
  src/domain/errors/index.ts
  src/factories/controller/academicGroup/createAcademicGroupControllerFactory.ts
  src/factories/controller/academicGroup/listAcademicGroupsByUserControllerFactory.ts
  src/factories/usecase/academicGroup/createAcademicGroupUsecaseFactory.ts
  src/factories/usecase/academicGroup/listAcademicGroupsByUserUsecaseFactory.ts
  src/http/controllers/academicGroup/createAcademicGroupController.ts
  src/http/controllers/academicGroup/listAcademicGroupsByUserController.ts
  src/http/error/errorHandler.ts
  src/http/routes/academicGroup.ts
  src/http/routes/index.ts
  src/http/routes/user.ts
  src/infra/repositories/academicGroup/academicGroupRepository.ts
  src/infra/repositories/academicGroup/memoryAcademicGroupRepository.ts
Labels: enhancement, help wanted

#8 Feature/academic group add member
  package.json
  src/app.ts
  src/application/dtos/classEnrollment.ts
  src/application/dtos/inscricaoDisciplina.ts
  src/application/repositories/academicGroupRepository.ts
  src/application/repositories/classEnrollmentRepository.ts
  src/application/usecases/academicGroup/addAcademicGroupMemberUsecase.ts
  src/factories/controller/academicGroup/addAcademicGroupMemberControllerFactory.ts
  src/factories/usecase/academicGroup/addAcademicGroupMemberUsecaseFactory.ts
  src/http/controllers/academicGroup/addAcademicGroupMemberController.ts
  src/http/routes/academicGroup.ts
  src/http/routes/user.ts
  src/infra/repositories/academicGroup/memoryAcademicGroupRepository.ts
  src/infra/repositories/classEnrollment/apiClassEnrollmentRepository.ts
  src/infra/repositories/user/memoryUserRepository.ts
  yarn.lock
Labels: enhancement
